source 'https://rubygems.org'

gem "rack", ">= 1.6.12"
gem "sinatra", ">= 1.3.5"
gem "test-unit"
gem "data_mapper"
gem "dm-mysql-adapter"
gem "dm-sqlite-adapter"
gem "bcrypt-ruby", :require => "bcrypt"
