source 'https://rubygems.org'

gem "rack", ">= 2.1.4"
gem "sinatra", ">= 2.0.0"
gem "test-unit"
gem "data_mapper"
gem "dm-mysql-adapter"
gem "dm-sqlite-adapter"
gem "bcrypt-ruby", :require => "bcrypt"
